"""
Security Alert Model
Represents high-fidelity security alerts generated by the detection and correlation engines.
"""

from dataclasses import dataclass, field, asdict
from datetime import datetime, timezone
from typing import Optional, List, Dict, Any
import uuid


def utc_now_iso() -> str:
    return datetime.now(timezone.utc).isoformat()


@dataclass
class Alert:
    alert_id: str = field(default_factory=lambda: f"ALT-{uuid.uuid4().hex[:8].upper()}")
    rule_id: str = "RULE-GENERIC"
    title: str = "Security Alert"
    description: str = ""
    severity: str = "MEDIUM"  # LOW, MEDIUM, HIGH, CRITICAL
    risk_score: int = 50       # 0 to 100
    
    # Context
    hostname: str = "unknown"
    device_id: str = "unknown"
    source_ip: Optional[str] = None
    destination_ip: Optional[str] = None
    username: Optional[str] = None
    
    # Timing & Aggregation
    first_seen: str = field(default_factory=utc_now_iso)
    last_seen: str = field(default_factory=utc_now_iso)
    event_count: int = 1
    
    # Workflow Status
    status: str = "OPEN"      # OPEN, ACKNOWLEDGED, RESOLVED
    
    # Evidence & Guidance
    matched_conditions: List[str] = field(default_factory=list)
    evidence_event_ids: List[str] = field(default_factory=list)
    recommendation: str = "Investigate the affected endpoint and review audit logs."
    mitre_technique: Optional[str] = None
    mitre_tactic: Optional[str] = None
    
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Alert':
        valid_keys = cls.__dataclass_fields__.keys()
        filtered = {k: v for k, v in data.items() if k in valid_keys}
        return cls(**filtered)
